### ISSUE TITLE
scaling image

### ISSUE THREAD

**Issue by eborbath** [kazuyanagimoto/quarto-slides-typst#1]
Hi! Thank you for the great template!

Could you please provide an example with how to scale and center an image when it's not generated with R, but rather embedded from an image file? I am thinking of something like? ` ![](/images/Picture1.png){width=80% align=center}`

**Comment by kazuyanagimoto** [comment]
You can do it using the Quarto syntax.

```md
![](/images/Picture1.png){width="80%" fig-align="center"}
```

I added an example of pictures to the demo slides.

**Comment by eborbath** [comment]
Thank you, this works well!
