### ISSUE TITLE
images side by side

### ISSUE THREAD

**Issue by eborbath** [kazuyanagimoto/quarto-slides-typst#4]
Hello,

Thanks again for the fantastic template! I would like to ask for your help with arranging 2+ figures side-by-side on a slide with custom captions. I have tried this:

```md
## Figures

![First figure](img/hokusai_kanagawa.jpg){width="30%" fig-align="left"}
![Second figure](img/hokusai_kanagawa.jpg){width="30%" fig-align="center"}
![Third figure](img/hokusai_kanagawa.jpg){width="30%" fig-align="right"}


```

It sort of works, but the captions do not show. Once I add captions, the order is messed up. 

I could get it to work with columns like this:

````md

## Multiple Columns {#sec-multicolumns}

```{=typst}
#slide[
```

[]{.alert}

![First figure](img/hokusai_kanagawa.jpg){width="50%" fig-align="left"}

```{=typst}
][
```

[]{.alert}

![Second figure](img/hokusai_kanagawa.jpg){width="50%" fig-align="left"}

```{=typst}
]
```
````

I was just wondering if there's maybe an easier solution.

**Comment by kazuyanagimoto** [comment]
I think this is what you want

```md

# Figures

::: {layout-ncol=3}

![First figure](img/hokusai_kanagawa.jpg)

![Second figure](img/hokusai_kanagawa.jpg)

![Third figure](img/hokusai_kanagawa.jpg)

:::

```

Please read [Quarto official document](https://quarto.org/docs/authoring/figures.html) for more flexible layouts. Now, I have noticed that Quarto's multicolumn layout is more simple and flexible than Touying's. I will update the demo slides and introduce these features.
