### ISSUE TITLE
removing "Figure X:" from figure caption

### ISSUE THREAD

**Issue by damlakeskekci** [kazuyanagimoto/quarto-slides-typst#5]
Hello,

Thanks a lot for the great template! I am looking for a way to remove the "Figure x:" part that is automatically added to figure captions. I was looking at [this page](https://quarto.org/docs/authoring/cross-reference-options.html) and tried experimenting with the `crossref` options in the front YAML. 

More specifically I have tried this:

````

---
title: Quarto Clean Theme
subtitle: A Minimalistic Theme for Quarto + Typst + Touying
format:
  clean-typst
crossref:
  fig-title: ""
  title-delim: ""
  fig-prefix: ""
---

::: {layout-ncol=3}

![First figure](img/hokusai_kanagawa.jpg){#fig-elephant}

![Second figure](img/hokusai_kanagawa.jpg){#fig-elephant}

![Third figure](img/hokusai_kanagawa.jpg){#fig-elephant}

:::

````

This removes the Figure part, but it leaves the "X: " prefix in front of all figure captions. How could I remove that?

**Comment by kazuyanagimoto** [comment]
As far as I know, there is no way to hide the caption numbering because captions will be referenced later (say, "As Figure 1 shows ...").
A workaround for putting titles on figures is putting them right after the figures as regular text.

````md
---
title: Quarto Clean Theme
subtitle: A Minimalistic Theme for Quarto + Typst + Touying
format:
  clean-typst
commands: [align]
---

::: {layout-ncol=3}

![](img/hokusai_kanagawa.jpg)
[{{< v -0.5em >}} First figure]{.align options="center"}

![](img/hokusai_kanagawa.jpg)
[{{< v -0.5em >}} Second figure]{.align options="center"}

![](img/hokusai_kanagawa.jpg)
[{{< v -0.5em >}} Third figure]{.align options="center"}

:::
```
